#### Grace Hadiyanto
#### e-mail: ifoundparis@gmail.com
#### Assignment 7
#### CS223P
#### Generated by django from python manage.py inspectdb command then edited

from __future__ import unicode_literals

from django.db import models

class Fortunes(models.Model):
    filename = models.CharField(max_length=255)
    size = models.IntegerField(blank=True, null=True)
    aphorism = models.TextField(blank=True)
    class Meta:
        managed = False
        db_table = 'fortunes'
    def __str__(self):
        return self.aphorism
